name: inference-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - openslide-python
  - pip:
      - tensorflow==2.17.0
      - opencv-python
      - pillow
      - numpy>=1.23.5,<2.0.0
      - matplotlib
